name: build

on: [push]

jobs:
  unit-tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: make unit-tests
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-env
      - run: make build
    needs: unit
