name: build

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make unit
  build:
    run:
      env:
        DEBUG: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: make build
      - run: make show
    needs: unit
